# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bef1d962e7e4dfd5a9abdcf9e48ef7e7b29de3af217cca52d95d5e37879b1e0b9f36ee637cade03d28a91f1e7707474f770fec79550503261eb354f2d74214b

test:
  secret_key_base: c9af823b6c0a6588b414707f96d849693bfd441cf33ff7eb0977749d01c0a492ac7702775790719878b0483ccb8e956bc91a0fe0f227535213cabcd8bb7e44ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
